# Generated by Django 4.0 on 2021-12-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=255)),
                ('film_description', models.TextField(max_length=255)),
                ('film_original_title', models.CharField(max_length=255)),
                ('film_year', models.IntegerField()),
                ('film_producer', models.CharField(max_length=255)),
                ('film_length', models.IntegerField()),
                ('film_premiere', models.DateField()),
                ('film_age_limit', models.IntegerField()),
                ('film_rent_start_date', models.DateField()),
                ('film_rent_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_author', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('review_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afisha.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='film_genre',
            field=models.ManyToManyField(to='afisha.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_roles',
            field=models.ManyToManyField(to='afisha.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_show_date',
            field=models.ManyToManyField(to='afisha.Show'),
        ),
    ]
