# Generated by Django 4.0 on 2021-12-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_film_film_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актер'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильм'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанр'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзыв'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Дата показа', 'verbose_name_plural': 'Дата показа'},
        ),
        migrations.AddField(
            model_name='film',
            name='is_film_in_rent',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_name',
            field=models.CharField(max_length=255, verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_age_limit',
            field=models.IntegerField(verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_genre',
            field=models.ManyToManyField(to='afisha.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_length',
            field=models.IntegerField(verbose_name='длительность фильма (мин)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_original_title',
            field=models.CharField(max_length=255, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_poster',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_premiere',
            field=models.DateField(verbose_name='Дата премьеры в мире'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_producer',
            field=models.CharField(max_length=255, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_rent_end_date',
            field=models.DateField(verbose_name='Конец проката'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_rent_start_date',
            field=models.DateField(verbose_name='Начало проката'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_roles',
            field=models.ManyToManyField(to='afisha.Actor', verbose_name='В главных ролях'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_show_date',
            field=models.ManyToManyField(to='afisha.Show', verbose_name='Дата показа'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=255, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.CharField(max_length=255, verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afisha.film', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateTimeField(verbose_name='Дата показа'),
        ),
    ]
