# Generated by Django 4.0 on 2021-12-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_alter_actor_options_alter_film_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_show_date',
        ),
        migrations.AddField(
            model_name='film',
            name='film_show_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afisha.show', verbose_name='Дата показа'),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_film_in_rent',
            field=models.BooleanField(default=1, verbose_name='В прокате ли'),
        ),
    ]
