# Generated by Django 4.0 on 2021-12-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0004_remove_film_film_show_date_film_film_show_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_show_date',
        ),
        migrations.AddField(
            model_name='show',
            name='show_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afisha.film'),
        ),
    ]
