# Generated by Django 4.0 on 2021-12-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0005_remove_film_film_show_date_show_show_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateTimeField(unique=True, verbose_name='Дата показа'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afisha.film', verbose_name='Фильм'),
        ),
    ]
